
version: '3.9'
services:
  knowledge_base:
    build:
      context: ../../  # Set the build context to the project root
      dockerfile: images/knowledgeBase_AirQualityIndexPredictionModel/Dockerfile
    image: isha1401/knowledgebase_airqualityindexpredictionmodel
    volumes:
      - ai_system:/tmp/knowledgeBase
    command:
      - sh
      - "-c"
      - |
        rm -rf /tmp/knowledgebase/ && cp -r /tmp/knowledgeBase/ /tmp/knowledgebase/;
volumes:
  ai_system:
    external: true