version: "3.0"
services:
  activation_base:
    image: activationbase_airqualityindexpredictionmodel
    volumes:
       - ai_system:/tmp
    command:
    - sh
    - "-c"
    - |
      rm -rf /tmp/activationBase/ && cp -r /activationBase/ /tmp/;
  knowledge_base:
    
    image: knowledgebase_airqualityindexpredictionmodel
    volumes:
       - ai_system:/tmp
    command:
    - sh
    - "-c"
    - |
      rm -rf /tmp/knowledgeBase/ && cp -r /knowledgeBase/ /tmp/;

  code_base:

    image: codebase_airqualityindexpredictionmodel
    volumes:
       - ai_system:/tmp
    depends_on:
      - "knowledge_base"
      - "activation_base"
    command:
    - sh
    - "-c"
    - |
      rm -rf /tmp/codeBase/ && cp -r /codeBase/ /tmp/;
      python /codeBase/RunOLSModel.py;
volumes:
  ai_system:
    external: true