version: '3.9'
services:
  code_base:
    build:
      context: ../../  # Set the build context to the project root
      dockerfile: images/codeBase_AirQualityIndexPredictionModel/Dockerfile
    image: isha1401/codebase_airqualityindexpredictionmodel
    volumes:
      - ai_system:/tmp/codeBase
    command:
      - sh
      - "-c"
      - |
        rm -rf /tmp/codebase/ && cp -r /tmp/codeBase/ /tmp/codebase/;
volumes:
  ai_system:
    external: true